@startuml

participant "System init"   as    System_init
participant "OLED"          as    OLED
participant "Buzzer"        as    Buzzer

== Notify the idle scrren ==

group Notify by OLED
System_init -> OLED: Display logo "Walkman"
activate OLED
OLED -> System_init: Return display logo finish status
deactivate OLED
end

group Notify by buzzer
System_init -> Buzzer: Make the rhythm "Mario"
activate Buzzer
Buzzer -> System_init: Return the make rhythm finish status
deactivate Buzzer
end

@enduml
