@startuml system_list_song_screen
actor User
participant "System main"   as    System_main
participant OLED
participant DFPLAYER

group interact with OLED
MainSystem -> OLED: Display list of songs
activate OLED
OLED -> MainSystem: List displayed with cursor at first song
deactivate OLED

MainSystem -> MainSystem: Transition to List Song State

loop Navigation
    User -> MainSystem: Click Left/Right button
    activate MainSystem
    MainSystem -> OLED: Move cursor up/down and update display
    activate OLED
    OLED -> MainSystem: Cursor updated
    deactivate OLED
    deactivate MainSystem
end

User -> MainSystem: Click Mid button
activate MainSystem

MainSystem -> MainSystem: Transition to Playing Song State
@enduml
