@startuml Initialization

actor User
participant "System init"   as    MainSystem
participant OLED            as    "oled"
participant DFPlayer        as    "dfplayer"
participant Buzzer          as    "buzzer"
participant RotationSensor  as    "rotation Sensor" 

User -> MainSystem: Power On
activate MainSystem

== Process view - System init manager ==

group I2C2 connect
MainSystem -> OLED: Init I2C2 
activate OLED
OLED -> MainSystem: Return I2C2 status
deactivate OLED
end

group UART2 connect
MainSystem -> DFPlayer: Init UART2
activate DFPlayer
DFPlayer -> MainSystem: Return UART2 status
deactivate DFPlayer
end


MainSystem -> Buzzer: Initialize (GPIO and timer setup)
activate Buzzer
Buzzer -> MainSystem: Initialization Complete
deactivate Buzzer

MainSystem -> RotationSensor: Initialize (ADC setup, calibration)
activate RotationSensor
RotationSensor -> MainSystem: Initialization Complete
deactivate RotationSensor

MainSystem -> OLED: Display logo
activate OLED
OLED -> MainSystem: Logo displayed
deactivate OLED

MainSystem -> Buzzer: Play "Mario" sound
activate Buzzer
Buzzer -> MainSystem: Sound played
deactivate Buzzer

deactivate MainSystem
@enduml
